apiVersion: v2
name: kafka-ha
description: Helm chart for Apache Kafka.
type: application

version: 15.0.0
appVersion: v3.6.1

maintainers:
  - name: sir5kong
    url: "https://github.com/itboon/kafka-docker"

keywords:
  - kafka
  - streaming
  - kraft
